// This file was generated by counterfeiter
package fakes

import (
	"sync"

	go_cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/pivotalservices/cf-mgmt/organization"
)

type FakeManager struct {
	InitializeLdapStub        func(ldapBindPassword string) error
	initializeLdapMutex       sync.RWMutex
	initializeLdapArgsForCall []struct {
		ldapBindPassword string
	}
	initializeLdapReturns struct {
		result1 error
	}
	ListOrgsStub        func() ([]go_cfclient.Org, error)
	listOrgsMutex       sync.RWMutex
	listOrgsArgsForCall []struct{}
	listOrgsReturns     struct {
		result1 []go_cfclient.Org
		result2 error
	}
	ListOrgSharedPrivateDomainsStub        func(orgGUID string) (map[string]go_cfclient.Domain, error)
	listOrgSharedPrivateDomainsMutex       sync.RWMutex
	listOrgSharedPrivateDomainsArgsForCall []struct {
		orgGUID string
	}
	listOrgSharedPrivateDomainsReturns struct {
		result1 map[string]go_cfclient.Domain
		result2 error
	}
	ListOrgOwnedPrivateDomainsStub        func(orgGUID string) (map[string]go_cfclient.Domain, error)
	listOrgOwnedPrivateDomainsMutex       sync.RWMutex
	listOrgOwnedPrivateDomainsArgsForCall []struct {
		orgGUID string
	}
	listOrgOwnedPrivateDomainsReturns struct {
		result1 map[string]go_cfclient.Domain
		result2 error
	}
	FindOrgStub        func(orgName string) (go_cfclient.Org, error)
	findOrgMutex       sync.RWMutex
	findOrgArgsForCall []struct {
		orgName string
	}
	findOrgReturns struct {
		result1 go_cfclient.Org
		result2 error
	}
	CreateOrgsStub        func() error
	createOrgsMutex       sync.RWMutex
	createOrgsArgsForCall []struct{}
	createOrgsReturns     struct {
		result1 error
	}
	CreatePrivateDomainsStub        func() error
	createPrivateDomainsMutex       sync.RWMutex
	createPrivateDomainsArgsForCall []struct{}
	createPrivateDomainsReturns     struct {
		result1 error
	}
	SharePrivateDomainsStub        func() error
	sharePrivateDomainsMutex       sync.RWMutex
	sharePrivateDomainsArgsForCall []struct{}
	sharePrivateDomainsReturns     struct {
		result1 error
	}
	DeleteOrgsStub        func() error
	deleteOrgsMutex       sync.RWMutex
	deleteOrgsArgsForCall []struct{}
	deleteOrgsReturns     struct {
		result1 error
	}
	UpdateOrgUsersStub        func() error
	updateOrgUsersMutex       sync.RWMutex
	updateOrgUsersArgsForCall []struct{}
	updateOrgUsersReturns     struct {
		result1 error
	}
	CreateQuotasStub        func() error
	createQuotasMutex       sync.RWMutex
	createQuotasArgsForCall []struct{}
	createQuotasReturns     struct {
		result1 error
	}
	GetOrgGUIDStub        func(orgName string) (string, error)
	getOrgGUIDMutex       sync.RWMutex
	getOrgGUIDArgsForCall []struct {
		orgName string
	}
	getOrgGUIDReturns struct {
		result1 string
		result2 error
	}
	ListOrgAuditorsStub        func(orgGUID string) (map[string]string, error)
	listOrgAuditorsMutex       sync.RWMutex
	listOrgAuditorsArgsForCall []struct {
		orgGUID string
	}
	listOrgAuditorsReturns struct {
		result1 map[string]string
		result2 error
	}
	ListOrgBillingManagerStub        func(orgGUID string) (map[string]string, error)
	listOrgBillingManagerMutex       sync.RWMutex
	listOrgBillingManagerArgsForCall []struct {
		orgGUID string
	}
	listOrgBillingManagerReturns struct {
		result1 map[string]string
		result2 error
	}
	ListOrgManagersStub        func(orgGUID string) (map[string]string, error)
	listOrgManagersMutex       sync.RWMutex
	listOrgManagersArgsForCall []struct {
		orgGUID string
	}
	listOrgManagersReturns struct {
		result1 map[string]string
		result2 error
	}
	OrgQuotaByNameStub        func(name string) (go_cfclient.OrgQuota, error)
	orgQuotaByNameMutex       sync.RWMutex
	orgQuotaByNameArgsForCall []struct {
		name string
	}
	orgQuotaByNameReturns struct {
		result1 go_cfclient.OrgQuota
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) InitializeLdap(ldapBindPassword string) error {
	fake.initializeLdapMutex.Lock()
	fake.initializeLdapArgsForCall = append(fake.initializeLdapArgsForCall, struct {
		ldapBindPassword string
	}{ldapBindPassword})
	fake.recordInvocation("InitializeLdap", []interface{}{ldapBindPassword})
	fake.initializeLdapMutex.Unlock()
	if fake.InitializeLdapStub != nil {
		return fake.InitializeLdapStub(ldapBindPassword)
	} else {
		return fake.initializeLdapReturns.result1
	}
}

func (fake *FakeManager) InitializeLdapCallCount() int {
	fake.initializeLdapMutex.RLock()
	defer fake.initializeLdapMutex.RUnlock()
	return len(fake.initializeLdapArgsForCall)
}

func (fake *FakeManager) InitializeLdapArgsForCall(i int) string {
	fake.initializeLdapMutex.RLock()
	defer fake.initializeLdapMutex.RUnlock()
	return fake.initializeLdapArgsForCall[i].ldapBindPassword
}

func (fake *FakeManager) InitializeLdapReturns(result1 error) {
	fake.InitializeLdapStub = nil
	fake.initializeLdapReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) ListOrgs() ([]go_cfclient.Org, error) {
	fake.listOrgsMutex.Lock()
	fake.listOrgsArgsForCall = append(fake.listOrgsArgsForCall, struct{}{})
	fake.recordInvocation("ListOrgs", []interface{}{})
	fake.listOrgsMutex.Unlock()
	if fake.ListOrgsStub != nil {
		return fake.ListOrgsStub()
	} else {
		return fake.listOrgsReturns.result1, fake.listOrgsReturns.result2
	}
}

func (fake *FakeManager) ListOrgsCallCount() int {
	fake.listOrgsMutex.RLock()
	defer fake.listOrgsMutex.RUnlock()
	return len(fake.listOrgsArgsForCall)
}

func (fake *FakeManager) ListOrgsReturns(result1 []go_cfclient.Org, result2 error) {
	fake.ListOrgsStub = nil
	fake.listOrgsReturns = struct {
		result1 []go_cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ListOrgSharedPrivateDomains(orgGUID string) (map[string]go_cfclient.Domain, error) {
	fake.listOrgSharedPrivateDomainsMutex.Lock()
	fake.listOrgSharedPrivateDomainsArgsForCall = append(fake.listOrgSharedPrivateDomainsArgsForCall, struct {
		orgGUID string
	}{orgGUID})
	fake.recordInvocation("ListOrgSharedPrivateDomains", []interface{}{orgGUID})
	fake.listOrgSharedPrivateDomainsMutex.Unlock()
	if fake.ListOrgSharedPrivateDomainsStub != nil {
		return fake.ListOrgSharedPrivateDomainsStub(orgGUID)
	} else {
		return fake.listOrgSharedPrivateDomainsReturns.result1, fake.listOrgSharedPrivateDomainsReturns.result2
	}
}

func (fake *FakeManager) ListOrgSharedPrivateDomainsCallCount() int {
	fake.listOrgSharedPrivateDomainsMutex.RLock()
	defer fake.listOrgSharedPrivateDomainsMutex.RUnlock()
	return len(fake.listOrgSharedPrivateDomainsArgsForCall)
}

func (fake *FakeManager) ListOrgSharedPrivateDomainsArgsForCall(i int) string {
	fake.listOrgSharedPrivateDomainsMutex.RLock()
	defer fake.listOrgSharedPrivateDomainsMutex.RUnlock()
	return fake.listOrgSharedPrivateDomainsArgsForCall[i].orgGUID
}

func (fake *FakeManager) ListOrgSharedPrivateDomainsReturns(result1 map[string]go_cfclient.Domain, result2 error) {
	fake.ListOrgSharedPrivateDomainsStub = nil
	fake.listOrgSharedPrivateDomainsReturns = struct {
		result1 map[string]go_cfclient.Domain
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ListOrgOwnedPrivateDomains(orgGUID string) (map[string]go_cfclient.Domain, error) {
	fake.listOrgOwnedPrivateDomainsMutex.Lock()
	fake.listOrgOwnedPrivateDomainsArgsForCall = append(fake.listOrgOwnedPrivateDomainsArgsForCall, struct {
		orgGUID string
	}{orgGUID})
	fake.recordInvocation("ListOrgOwnedPrivateDomains", []interface{}{orgGUID})
	fake.listOrgOwnedPrivateDomainsMutex.Unlock()
	if fake.ListOrgOwnedPrivateDomainsStub != nil {
		return fake.ListOrgOwnedPrivateDomainsStub(orgGUID)
	} else {
		return fake.listOrgOwnedPrivateDomainsReturns.result1, fake.listOrgOwnedPrivateDomainsReturns.result2
	}
}

func (fake *FakeManager) ListOrgOwnedPrivateDomainsCallCount() int {
	fake.listOrgOwnedPrivateDomainsMutex.RLock()
	defer fake.listOrgOwnedPrivateDomainsMutex.RUnlock()
	return len(fake.listOrgOwnedPrivateDomainsArgsForCall)
}

func (fake *FakeManager) ListOrgOwnedPrivateDomainsArgsForCall(i int) string {
	fake.listOrgOwnedPrivateDomainsMutex.RLock()
	defer fake.listOrgOwnedPrivateDomainsMutex.RUnlock()
	return fake.listOrgOwnedPrivateDomainsArgsForCall[i].orgGUID
}

func (fake *FakeManager) ListOrgOwnedPrivateDomainsReturns(result1 map[string]go_cfclient.Domain, result2 error) {
	fake.ListOrgOwnedPrivateDomainsStub = nil
	fake.listOrgOwnedPrivateDomainsReturns = struct {
		result1 map[string]go_cfclient.Domain
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) FindOrg(orgName string) (go_cfclient.Org, error) {
	fake.findOrgMutex.Lock()
	fake.findOrgArgsForCall = append(fake.findOrgArgsForCall, struct {
		orgName string
	}{orgName})
	fake.recordInvocation("FindOrg", []interface{}{orgName})
	fake.findOrgMutex.Unlock()
	if fake.FindOrgStub != nil {
		return fake.FindOrgStub(orgName)
	} else {
		return fake.findOrgReturns.result1, fake.findOrgReturns.result2
	}
}

func (fake *FakeManager) FindOrgCallCount() int {
	fake.findOrgMutex.RLock()
	defer fake.findOrgMutex.RUnlock()
	return len(fake.findOrgArgsForCall)
}

func (fake *FakeManager) FindOrgArgsForCall(i int) string {
	fake.findOrgMutex.RLock()
	defer fake.findOrgMutex.RUnlock()
	return fake.findOrgArgsForCall[i].orgName
}

func (fake *FakeManager) FindOrgReturns(result1 go_cfclient.Org, result2 error) {
	fake.FindOrgStub = nil
	fake.findOrgReturns = struct {
		result1 go_cfclient.Org
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) CreateOrgs() error {
	fake.createOrgsMutex.Lock()
	fake.createOrgsArgsForCall = append(fake.createOrgsArgsForCall, struct{}{})
	fake.recordInvocation("CreateOrgs", []interface{}{})
	fake.createOrgsMutex.Unlock()
	if fake.CreateOrgsStub != nil {
		return fake.CreateOrgsStub()
	} else {
		return fake.createOrgsReturns.result1
	}
}

func (fake *FakeManager) CreateOrgsCallCount() int {
	fake.createOrgsMutex.RLock()
	defer fake.createOrgsMutex.RUnlock()
	return len(fake.createOrgsArgsForCall)
}

func (fake *FakeManager) CreateOrgsReturns(result1 error) {
	fake.CreateOrgsStub = nil
	fake.createOrgsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) CreatePrivateDomains() error {
	fake.createPrivateDomainsMutex.Lock()
	fake.createPrivateDomainsArgsForCall = append(fake.createPrivateDomainsArgsForCall, struct{}{})
	fake.recordInvocation("CreatePrivateDomains", []interface{}{})
	fake.createPrivateDomainsMutex.Unlock()
	if fake.CreatePrivateDomainsStub != nil {
		return fake.CreatePrivateDomainsStub()
	} else {
		return fake.createPrivateDomainsReturns.result1
	}
}

func (fake *FakeManager) CreatePrivateDomainsCallCount() int {
	fake.createPrivateDomainsMutex.RLock()
	defer fake.createPrivateDomainsMutex.RUnlock()
	return len(fake.createPrivateDomainsArgsForCall)
}

func (fake *FakeManager) CreatePrivateDomainsReturns(result1 error) {
	fake.CreatePrivateDomainsStub = nil
	fake.createPrivateDomainsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) SharePrivateDomains() error {
	fake.sharePrivateDomainsMutex.Lock()
	fake.sharePrivateDomainsArgsForCall = append(fake.sharePrivateDomainsArgsForCall, struct{}{})
	fake.recordInvocation("SharePrivateDomains", []interface{}{})
	fake.sharePrivateDomainsMutex.Unlock()
	if fake.SharePrivateDomainsStub != nil {
		return fake.SharePrivateDomainsStub()
	} else {
		return fake.sharePrivateDomainsReturns.result1
	}
}

func (fake *FakeManager) SharePrivateDomainsCallCount() int {
	fake.sharePrivateDomainsMutex.RLock()
	defer fake.sharePrivateDomainsMutex.RUnlock()
	return len(fake.sharePrivateDomainsArgsForCall)
}

func (fake *FakeManager) SharePrivateDomainsReturns(result1 error) {
	fake.SharePrivateDomainsStub = nil
	fake.sharePrivateDomainsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) DeleteOrgs() error {
	fake.deleteOrgsMutex.Lock()
	fake.deleteOrgsArgsForCall = append(fake.deleteOrgsArgsForCall, struct{}{})
	fake.recordInvocation("DeleteOrgs", []interface{}{})
	fake.deleteOrgsMutex.Unlock()
	if fake.DeleteOrgsStub != nil {
		return fake.DeleteOrgsStub()
	} else {
		return fake.deleteOrgsReturns.result1
	}
}

func (fake *FakeManager) DeleteOrgsCallCount() int {
	fake.deleteOrgsMutex.RLock()
	defer fake.deleteOrgsMutex.RUnlock()
	return len(fake.deleteOrgsArgsForCall)
}

func (fake *FakeManager) DeleteOrgsReturns(result1 error) {
	fake.DeleteOrgsStub = nil
	fake.deleteOrgsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) UpdateOrgUsers() error {
	fake.updateOrgUsersMutex.Lock()
	fake.updateOrgUsersArgsForCall = append(fake.updateOrgUsersArgsForCall, struct{}{})
	fake.recordInvocation("UpdateOrgUsers", []interface{}{})
	fake.updateOrgUsersMutex.Unlock()
	if fake.UpdateOrgUsersStub != nil {
		return fake.UpdateOrgUsersStub()
	} else {
		return fake.updateOrgUsersReturns.result1
	}
}

func (fake *FakeManager) UpdateOrgUsersCallCount() int {
	fake.updateOrgUsersMutex.RLock()
	defer fake.updateOrgUsersMutex.RUnlock()
	return len(fake.updateOrgUsersArgsForCall)
}

func (fake *FakeManager) UpdateOrgUsersReturns(result1 error) {
	fake.UpdateOrgUsersStub = nil
	fake.updateOrgUsersReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) CreateQuotas() error {
	fake.createQuotasMutex.Lock()
	fake.createQuotasArgsForCall = append(fake.createQuotasArgsForCall, struct{}{})
	fake.recordInvocation("CreateQuotas", []interface{}{})
	fake.createQuotasMutex.Unlock()
	if fake.CreateQuotasStub != nil {
		return fake.CreateQuotasStub()
	} else {
		return fake.createQuotasReturns.result1
	}
}

func (fake *FakeManager) CreateQuotasCallCount() int {
	fake.createQuotasMutex.RLock()
	defer fake.createQuotasMutex.RUnlock()
	return len(fake.createQuotasArgsForCall)
}

func (fake *FakeManager) CreateQuotasReturns(result1 error) {
	fake.CreateQuotasStub = nil
	fake.createQuotasReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) GetOrgGUID(orgName string) (string, error) {
	fake.getOrgGUIDMutex.Lock()
	fake.getOrgGUIDArgsForCall = append(fake.getOrgGUIDArgsForCall, struct {
		orgName string
	}{orgName})
	fake.recordInvocation("GetOrgGUID", []interface{}{orgName})
	fake.getOrgGUIDMutex.Unlock()
	if fake.GetOrgGUIDStub != nil {
		return fake.GetOrgGUIDStub(orgName)
	} else {
		return fake.getOrgGUIDReturns.result1, fake.getOrgGUIDReturns.result2
	}
}

func (fake *FakeManager) GetOrgGUIDCallCount() int {
	fake.getOrgGUIDMutex.RLock()
	defer fake.getOrgGUIDMutex.RUnlock()
	return len(fake.getOrgGUIDArgsForCall)
}

func (fake *FakeManager) GetOrgGUIDArgsForCall(i int) string {
	fake.getOrgGUIDMutex.RLock()
	defer fake.getOrgGUIDMutex.RUnlock()
	return fake.getOrgGUIDArgsForCall[i].orgName
}

func (fake *FakeManager) GetOrgGUIDReturns(result1 string, result2 error) {
	fake.GetOrgGUIDStub = nil
	fake.getOrgGUIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ListOrgAuditors(orgGUID string) (map[string]string, error) {
	fake.listOrgAuditorsMutex.Lock()
	fake.listOrgAuditorsArgsForCall = append(fake.listOrgAuditorsArgsForCall, struct {
		orgGUID string
	}{orgGUID})
	fake.recordInvocation("ListOrgAuditors", []interface{}{orgGUID})
	fake.listOrgAuditorsMutex.Unlock()
	if fake.ListOrgAuditorsStub != nil {
		return fake.ListOrgAuditorsStub(orgGUID)
	} else {
		return fake.listOrgAuditorsReturns.result1, fake.listOrgAuditorsReturns.result2
	}
}

func (fake *FakeManager) ListOrgAuditorsCallCount() int {
	fake.listOrgAuditorsMutex.RLock()
	defer fake.listOrgAuditorsMutex.RUnlock()
	return len(fake.listOrgAuditorsArgsForCall)
}

func (fake *FakeManager) ListOrgAuditorsArgsForCall(i int) string {
	fake.listOrgAuditorsMutex.RLock()
	defer fake.listOrgAuditorsMutex.RUnlock()
	return fake.listOrgAuditorsArgsForCall[i].orgGUID
}

func (fake *FakeManager) ListOrgAuditorsReturns(result1 map[string]string, result2 error) {
	fake.ListOrgAuditorsStub = nil
	fake.listOrgAuditorsReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ListOrgBillingManager(orgGUID string) (map[string]string, error) {
	fake.listOrgBillingManagerMutex.Lock()
	fake.listOrgBillingManagerArgsForCall = append(fake.listOrgBillingManagerArgsForCall, struct {
		orgGUID string
	}{orgGUID})
	fake.recordInvocation("ListOrgBillingManager", []interface{}{orgGUID})
	fake.listOrgBillingManagerMutex.Unlock()
	if fake.ListOrgBillingManagerStub != nil {
		return fake.ListOrgBillingManagerStub(orgGUID)
	} else {
		return fake.listOrgBillingManagerReturns.result1, fake.listOrgBillingManagerReturns.result2
	}
}

func (fake *FakeManager) ListOrgBillingManagerCallCount() int {
	fake.listOrgBillingManagerMutex.RLock()
	defer fake.listOrgBillingManagerMutex.RUnlock()
	return len(fake.listOrgBillingManagerArgsForCall)
}

func (fake *FakeManager) ListOrgBillingManagerArgsForCall(i int) string {
	fake.listOrgBillingManagerMutex.RLock()
	defer fake.listOrgBillingManagerMutex.RUnlock()
	return fake.listOrgBillingManagerArgsForCall[i].orgGUID
}

func (fake *FakeManager) ListOrgBillingManagerReturns(result1 map[string]string, result2 error) {
	fake.ListOrgBillingManagerStub = nil
	fake.listOrgBillingManagerReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ListOrgManagers(orgGUID string) (map[string]string, error) {
	fake.listOrgManagersMutex.Lock()
	fake.listOrgManagersArgsForCall = append(fake.listOrgManagersArgsForCall, struct {
		orgGUID string
	}{orgGUID})
	fake.recordInvocation("ListOrgManagers", []interface{}{orgGUID})
	fake.listOrgManagersMutex.Unlock()
	if fake.ListOrgManagersStub != nil {
		return fake.ListOrgManagersStub(orgGUID)
	} else {
		return fake.listOrgManagersReturns.result1, fake.listOrgManagersReturns.result2
	}
}

func (fake *FakeManager) ListOrgManagersCallCount() int {
	fake.listOrgManagersMutex.RLock()
	defer fake.listOrgManagersMutex.RUnlock()
	return len(fake.listOrgManagersArgsForCall)
}

func (fake *FakeManager) ListOrgManagersArgsForCall(i int) string {
	fake.listOrgManagersMutex.RLock()
	defer fake.listOrgManagersMutex.RUnlock()
	return fake.listOrgManagersArgsForCall[i].orgGUID
}

func (fake *FakeManager) ListOrgManagersReturns(result1 map[string]string, result2 error) {
	fake.ListOrgManagersStub = nil
	fake.listOrgManagersReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) OrgQuotaByName(name string) (go_cfclient.OrgQuota, error) {
	fake.orgQuotaByNameMutex.Lock()
	fake.orgQuotaByNameArgsForCall = append(fake.orgQuotaByNameArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("OrgQuotaByName", []interface{}{name})
	fake.orgQuotaByNameMutex.Unlock()
	if fake.OrgQuotaByNameStub != nil {
		return fake.OrgQuotaByNameStub(name)
	} else {
		return fake.orgQuotaByNameReturns.result1, fake.orgQuotaByNameReturns.result2
	}
}

func (fake *FakeManager) OrgQuotaByNameCallCount() int {
	fake.orgQuotaByNameMutex.RLock()
	defer fake.orgQuotaByNameMutex.RUnlock()
	return len(fake.orgQuotaByNameArgsForCall)
}

func (fake *FakeManager) OrgQuotaByNameArgsForCall(i int) string {
	fake.orgQuotaByNameMutex.RLock()
	defer fake.orgQuotaByNameMutex.RUnlock()
	return fake.orgQuotaByNameArgsForCall[i].name
}

func (fake *FakeManager) OrgQuotaByNameReturns(result1 go_cfclient.OrgQuota, result2 error) {
	fake.OrgQuotaByNameStub = nil
	fake.orgQuotaByNameReturns = struct {
		result1 go_cfclient.OrgQuota
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.initializeLdapMutex.RLock()
	defer fake.initializeLdapMutex.RUnlock()
	fake.listOrgsMutex.RLock()
	defer fake.listOrgsMutex.RUnlock()
	fake.listOrgSharedPrivateDomainsMutex.RLock()
	defer fake.listOrgSharedPrivateDomainsMutex.RUnlock()
	fake.listOrgOwnedPrivateDomainsMutex.RLock()
	defer fake.listOrgOwnedPrivateDomainsMutex.RUnlock()
	fake.findOrgMutex.RLock()
	defer fake.findOrgMutex.RUnlock()
	fake.createOrgsMutex.RLock()
	defer fake.createOrgsMutex.RUnlock()
	fake.createPrivateDomainsMutex.RLock()
	defer fake.createPrivateDomainsMutex.RUnlock()
	fake.sharePrivateDomainsMutex.RLock()
	defer fake.sharePrivateDomainsMutex.RUnlock()
	fake.deleteOrgsMutex.RLock()
	defer fake.deleteOrgsMutex.RUnlock()
	fake.updateOrgUsersMutex.RLock()
	defer fake.updateOrgUsersMutex.RUnlock()
	fake.createQuotasMutex.RLock()
	defer fake.createQuotasMutex.RUnlock()
	fake.getOrgGUIDMutex.RLock()
	defer fake.getOrgGUIDMutex.RUnlock()
	fake.listOrgAuditorsMutex.RLock()
	defer fake.listOrgAuditorsMutex.RUnlock()
	fake.listOrgBillingManagerMutex.RLock()
	defer fake.listOrgBillingManagerMutex.RUnlock()
	fake.listOrgManagersMutex.RLock()
	defer fake.listOrgManagersMutex.RUnlock()
	fake.orgQuotaByNameMutex.RLock()
	defer fake.orgQuotaByNameMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ organization.Manager = new(FakeManager)
