platform: linux
image_resource:
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/buildroot
    tag: git
run:
  path: source/ci/tasks/prepare.sh
inputs:
- name: source
- name: releases
outputs:
- name: prepare-output
