platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: latest

inputs:
- name: source
- name: cf-deployment-env

params:
  SYSTEM_DOMAIN:

run:
  path: source/ci/tasks/runIntegrationTests.sh

