// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	uaaa "github.com/cloudfoundry-community/go-uaa"
)

type FakeUaa struct {
	CreateUserStub        func(uaaa.User) (*uaaa.User, error)
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 uaaa.User
	}
	createUserReturns struct {
		result1 *uaaa.User
		result2 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 *uaaa.User
		result2 error
	}
	ListUsersStub        func(string, string, string, uaaa.SortOrder, int, int) ([]uaaa.User, uaaa.Page, error)
	listUsersMutex       sync.RWMutex
	listUsersArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 uaaa.SortOrder
		arg5 int
		arg6 int
	}
	listUsersReturns struct {
		result1 []uaaa.User
		result2 uaaa.Page
		result3 error
	}
	listUsersReturnsOnCall map[int]struct {
		result1 []uaaa.User
		result2 uaaa.Page
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUaa) CreateUser(arg1 uaaa.User) (*uaaa.User, error) {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 uaaa.User
	}{arg1})
	stub := fake.CreateUserStub
	fakeReturns := fake.createUserReturns
	fake.recordInvocation("CreateUser", []interface{}{arg1})
	fake.createUserMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUaa) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeUaa) CreateUserCalls(stub func(uaaa.User) (*uaaa.User, error)) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *FakeUaa) CreateUserArgsForCall(i int) uaaa.User {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeUaa) CreateUserReturns(result1 *uaaa.User, result2 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 *uaaa.User
		result2 error
	}{result1, result2}
}

func (fake *FakeUaa) CreateUserReturnsOnCall(i int, result1 *uaaa.User, result2 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 *uaaa.User
			result2 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 *uaaa.User
		result2 error
	}{result1, result2}
}

func (fake *FakeUaa) ListUsers(arg1 string, arg2 string, arg3 string, arg4 uaaa.SortOrder, arg5 int, arg6 int) ([]uaaa.User, uaaa.Page, error) {
	fake.listUsersMutex.Lock()
	ret, specificReturn := fake.listUsersReturnsOnCall[len(fake.listUsersArgsForCall)]
	fake.listUsersArgsForCall = append(fake.listUsersArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 uaaa.SortOrder
		arg5 int
		arg6 int
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.ListUsersStub
	fakeReturns := fake.listUsersReturns
	fake.recordInvocation("ListUsers", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.listUsersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeUaa) ListUsersCallCount() int {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	return len(fake.listUsersArgsForCall)
}

func (fake *FakeUaa) ListUsersCalls(stub func(string, string, string, uaaa.SortOrder, int, int) ([]uaaa.User, uaaa.Page, error)) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = stub
}

func (fake *FakeUaa) ListUsersArgsForCall(i int) (string, string, string, uaaa.SortOrder, int, int) {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	argsForCall := fake.listUsersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeUaa) ListUsersReturns(result1 []uaaa.User, result2 uaaa.Page, result3 error) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	fake.listUsersReturns = struct {
		result1 []uaaa.User
		result2 uaaa.Page
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeUaa) ListUsersReturnsOnCall(i int, result1 []uaaa.User, result2 uaaa.Page, result3 error) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	if fake.listUsersReturnsOnCall == nil {
		fake.listUsersReturnsOnCall = make(map[int]struct {
			result1 []uaaa.User
			result2 uaaa.Page
			result3 error
		})
	}
	fake.listUsersReturnsOnCall[i] = struct {
		result1 []uaaa.User
		result2 uaaa.Page
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeUaa) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUaa) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
